# Site settings
title: Barbara Kastelin
email: marc.g.smith@gmail.com
description: Barbara Kastelin &#8211; Author of The Parrot Tree
baseurl: ""
url: "http://www.barbarakastelin.co.uk"

# Build settings
markdown: kramdown

sass:
    sass_dir: /_scss

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default-layout"
